import type {
  MachinePerformanceReviewGuideResponseDtoType,
  MachinePerformanceReviewImprovementResponseDtoType,
  MachinePerformanceReviewMeasurementResponseDtoType,
  MachinePerformanceReviewOperationStatusResponseDtoType,
  MachinePerformanceReviewSummaryResponseDtoType,
  MachinePerformanceReviewYearlyPlanResponseDtoType
} from '@core/types'

// 성능점검시 검토사항 시드 생성 함수들

export function makeResultSummarySeed(resultSummary?: MachinePerformanceReviewSummaryResponseDtoType) {
  return {
    maintenanceGuidelineAdequacy: resultSummary?.maintenanceGuidelineAdequacy || '',
    systemOperationalStatus: resultSummary?.systemOperationalStatus || '',
    designAndMeasuredValueConsistency: resultSummary?.designAndMeasuredValueConsistency || '',
    equipmentAgingDegree: resultSummary?.equipmentAgingDegree || '',
    inspectionDeficiencies: resultSummary?.inspectionDeficiencies || '',
    improvementNeedsAndPlan: resultSummary?.improvementNeedsAndPlan || '',
    energyUsageByType: resultSummary?.energyUsageByType || '',
    energyEfficiencyOperationMethod: resultSummary?.energyEfficiencyOperationMethod || ''
  }
}

export function makeGuideSeed(guide?: MachinePerformanceReviewGuideResponseDtoType) {
  return {
    builtDrawingYn: guide?.builtDrawingYn || 'Y',
    specificationYn: guide?.specificationYn || 'Y',
    loadCalculationYn: guide?.loadCalculationYn || 'Y',
    operationManual: guide?.operationManual || 'Y',
    manufacturerCertificateYn: guide?.manufacturerCertificateYn || 'Y',
    techStandardForm3Yn: guide?.techStandardForm3Yn || 'Y',
    techStandardForm4Yn: guide?.techStandardForm4Yn || 'Y',
    techStandardForm5Yn: guide?.techStandardForm5Yn || 'Y',
    techStandardForm6Yn: guide?.techStandardForm6Yn || 'Y'
  }
}

export function makeOperationStatusSeed(operationStatus?: MachinePerformanceReviewOperationStatusResponseDtoType) {
  return {
    // Result 필드는 'NONE'으로 초기화
    refrigeratorResult: operationStatus?.refrigeratorResult ?? 'NONE',
    coolingTowerResult: operationStatus?.coolingTowerResult ?? 'NONE',
    thermalStorageResult: operationStatus?.thermalStorageResult ?? 'NONE',
    boilerResult: operationStatus?.boilerResult ?? 'NONE',
    heatExchangerResult: operationStatus?.heatExchangerResult ?? 'NONE',
    expansionTankResult: operationStatus?.expansionTankResult ?? 'NONE',
    pumpResult: operationStatus?.pumpResult ?? 'NONE',
    renewableEnergySystemResult: operationStatus?.renewableEnergySystemResult ?? 'NONE',
    packageAirConditionerResult: operationStatus?.packageAirConditionerResult ?? 'NONE',
    precisionAirConditionerResult: operationStatus?.precisionAirConditionerResult ?? 'NONE',
    airHandlingUnitResult: operationStatus?.airHandlingUnitResult ?? 'NONE',
    fanCoilUnitResult: operationStatus?.fanCoilUnitResult ?? 'NONE',
    ventilationSystemResult: operationStatus?.ventilationSystemResult ?? 'NONE',
    filterResult: operationStatus?.filterResult ?? 'NONE',
    sanitaryFacilityResult: operationStatus?.sanitaryFacilityResult ?? 'NONE',
    hotWaterSupplyResult: operationStatus?.hotWaterSupplyResult ?? 'NONE',
    waterTankResult: operationStatus?.waterTankResult ?? 'NONE',
    drainageResult: operationStatus?.drainageResult ?? 'NONE',
    sewageTreatmentResult: operationStatus?.sewageTreatmentResult ?? 'NONE',
    waterReuseResult: operationStatus?.waterReuseResult ?? 'NONE',
    pipeLineResult: operationStatus?.pipeLineResult ?? 'NONE',
    ductResult: operationStatus?.ductResult ?? 'NONE',
    insulationResult: operationStatus?.insulationResult ?? 'NONE',
    automaticControlResult: operationStatus?.automaticControlResult ?? 'NONE',
    noiseVibrationSeismicResult: operationStatus?.noiseVibrationSeismicResult ?? 'NONE',

    // Remark 및 Opinion 필드는 ''으로 초기화
    refrigeratorRemark: operationStatus?.refrigeratorRemark ?? '',
    coolingTowerRemark: operationStatus?.coolingTowerRemark ?? '',
    thermalStorageRemark: operationStatus?.thermalStorageRemark ?? '',
    boilerRemark: operationStatus?.boilerRemark ?? '',
    heatExchangerRemark: operationStatus?.heatExchangerRemark ?? '',
    expansionTankRemark: operationStatus?.expansionTankRemark ?? '',
    pumpRemark: operationStatus?.pumpRemark ?? '',
    renewableEnergySystemRemark: operationStatus?.renewableEnergySystemRemark ?? '',
    packageAirConditionerRemark: operationStatus?.packageAirConditionerRemark ?? '',
    precisionAirConditionerRemark: operationStatus?.precisionAirConditionerRemark ?? '',
    airHandlingUnitRemark: operationStatus?.airHandlingUnitRemark ?? '',
    fanCoilUnitRemark: operationStatus?.fanCoilUnitRemark ?? '',
    ventilationSystemRemark: operationStatus?.ventilationSystemRemark ?? '',
    filterRemark: operationStatus?.filterRemark ?? '',
    sanitaryFacilityRemark: operationStatus?.sanitaryFacilityRemark ?? '',
    hotWaterSupplyRemark: operationStatus?.hotWaterSupplyRemark ?? '',
    waterTankRemark: operationStatus?.waterTankRemark ?? '',
    drainageRemark: operationStatus?.drainageRemark ?? '',
    sewageTreatmentRemark: operationStatus?.sewageTreatmentRemark ?? '',
    waterReuseRemark: operationStatus?.waterReuseRemark ?? '',
    pipeLineRemark: operationStatus?.pipeLineRemark ?? '',
    ductRemark: operationStatus?.ductRemark ?? '',
    insulationRemark: operationStatus?.insulationRemark ?? '',
    automaticControlRemark: operationStatus?.automaticControlRemark ?? '',
    noiseVibrationSeismicRemark: operationStatus?.noiseVibrationSeismicRemark ?? '',
    opinion: operationStatus?.opinion ?? ''
  }
}

export function makeMeasurementSeed(measurement?: MachinePerformanceReviewMeasurementResponseDtoType) {
  return {
    // Result 필드는 'NONE'으로 초기화
    refrigeratorResult: measurement?.refrigeratorResult ?? 'NONE',
    coolingTowerResult: measurement?.coolingTowerResult ?? 'NONE',
    thermalStorageResult: measurement?.thermalStorageResult ?? 'NONE',
    boilerResult: measurement?.boilerResult ?? 'NONE',
    heatExchangerResult: measurement?.heatExchangerResult ?? 'NONE',
    expansionTankResult: measurement?.expansionTankResult ?? 'NONE',
    pumpResult: measurement?.pumpResult ?? 'NONE',
    renewableEnergySystemResult: measurement?.renewableEnergySystemResult ?? 'NONE',
    packageAirConditionerResult: measurement?.packageAirConditionerResult ?? 'NONE',
    precisionAirConditionerResult: measurement?.precisionAirConditionerResult ?? 'NONE',
    airHandlingUnitResult: measurement?.airHandlingUnitResult ?? 'NONE',
    fanCoilUnitResult: measurement?.fanCoilUnitResult ?? 'NONE',
    ventilationSystemResult: measurement?.ventilationSystemResult ?? 'NONE',
    filterResult: measurement?.filterResult ?? 'NONE',
    sanitaryFacilityResult: measurement?.sanitaryFacilityResult ?? 'NONE',
    hotWaterSupplyResult: measurement?.hotWaterSupplyResult ?? 'NONE',
    waterTankResult: measurement?.waterTankResult ?? 'NONE',
    drainageResult: measurement?.drainageResult ?? 'NONE',
    sewageTreatmentResult: measurement?.sewageTreatmentResult ?? 'NONE',
    waterReuseResult: measurement?.waterReuseResult ?? 'NONE',
    pipeLineResult: measurement?.pipeLineResult ?? 'NONE',
    ductResult: measurement?.ductResult ?? 'NONE',
    insulationResult: measurement?.insulationResult ?? 'NONE',
    automaticControlResult: measurement?.automaticControlResult ?? 'NONE',
    noiseVibrationSeismicResult: measurement?.noiseVibrationSeismicResult ?? 'NONE',

    // Remark 및 Opinion 필드는 ''으로 초기화
    refrigeratorRemark: measurement?.refrigeratorRemark ?? '',
    coolingTowerRemark: measurement?.coolingTowerRemark ?? '',
    thermalStorageRemark: measurement?.thermalStorageRemark ?? '',
    boilerRemark: measurement?.boilerRemark ?? '',
    heatExchangerRemark: measurement?.heatExchangerRemark ?? '',
    expansionTankRemark: measurement?.expansionTankRemark ?? '',
    pumpRemark: measurement?.pumpRemark ?? '',
    renewableEnergySystemRemark: measurement?.renewableEnergySystemRemark ?? '',
    packageAirConditionerRemark: measurement?.packageAirConditionerRemark ?? '',
    precisionAirConditionerRemark: measurement?.precisionAirConditionerRemark ?? '',
    airHandlingUnitRemark: measurement?.airHandlingUnitRemark ?? '',
    fanCoilUnitRemark: measurement?.fanCoilUnitRemark ?? '',
    ventilationSystemRemark: measurement?.ventilationSystemRemark ?? '',
    filterRemark: measurement?.filterRemark ?? '',
    sanitaryFacilityRemark: measurement?.sanitaryFacilityRemark ?? '',
    hotWaterSupplyRemark: measurement?.hotWaterSupplyRemark ?? '',
    waterTankRemark: measurement?.waterTankRemark ?? '',
    drainageRemark: measurement?.drainageRemark ?? '',
    sewageTreatmentRemark: measurement?.sewageTreatmentRemark ?? '',
    waterReuseRemark: measurement?.waterReuseRemark ?? '',
    pipeLineRemark: measurement?.pipeLineRemark ?? '',
    ductRemark: measurement?.ductRemark ?? '',
    insulationRemark: measurement?.insulationRemark ?? '',
    automaticControlRemark: measurement?.automaticControlRemark ?? '',
    noiseVibrationSeismicRemark: measurement?.noiseVibrationSeismicRemark ?? '',
    opinion: measurement?.opinion ?? ''
  }
}

export function makeImprovementSeed(improvement?: MachinePerformanceReviewImprovementResponseDtoType) {
  return {
    refrigeratorResult: improvement?.refrigeratorResult ?? 'NONE',
    coolingTowerResult: improvement?.coolingTowerResult ?? 'NONE',
    thermalStorageResult: improvement?.thermalStorageResult ?? 'NONE',
    boilerResult: improvement?.boilerResult ?? 'NONE',
    heatExchangerResult: improvement?.heatExchangerResult ?? 'NONE',
    expansionTankResult: improvement?.expansionTankResult ?? 'NONE',
    pumpResult: improvement?.pumpResult ?? 'NONE',
    renewableEnergySystemResult: improvement?.renewableEnergySystemResult ?? 'NONE',
    packageAirConditionerResult: improvement?.packageAirConditionerResult ?? 'NONE',
    precisionAirConditionerResult: improvement?.precisionAirConditionerResult ?? 'NONE',
    airHandlingUnitResult: improvement?.airHandlingUnitResult ?? 'NONE',
    fanCoilUnitResult: improvement?.fanCoilUnitResult ?? 'NONE',
    ventilationSystemResult: improvement?.ventilationSystemResult ?? 'NONE',
    filterResult: improvement?.filterResult ?? 'NONE',
    sanitaryFacilityResult: improvement?.sanitaryFacilityResult ?? 'NONE',
    hotWaterSupplyResult: improvement?.hotWaterSupplyResult ?? 'NONE',
    waterTankResult: improvement?.waterTankResult ?? 'NONE',
    drainageResult: improvement?.drainageResult ?? 'NONE',
    sewageTreatmentResult: improvement?.sewageTreatmentResult ?? 'NONE',
    waterReuseResult: improvement?.waterReuseResult ?? 'NONE',
    pipeLineResult: improvement?.pipeLineResult ?? 'NONE',
    ductResult: improvement?.ductResult ?? 'NONE',
    insulationResult: improvement?.insulationResult ?? 'NONE',
    automaticControlResult: improvement?.automaticControlResult ?? 'NONE',
    noiseVibrationSeismicResult: improvement?.noiseVibrationSeismicResult ?? 'NONE',

    // Deficiency 및 Opinion 필드는 ''으로 초기화
    refrigeratorDeficiency: improvement?.refrigeratorDeficiency ?? '',
    coolingTowerDeficiency: improvement?.coolingTowerDeficiency ?? '',
    thermalStorageDeficiency: improvement?.thermalStorageDeficiency ?? '',
    boilerDeficiency: improvement?.boilerDeficiency ?? '',
    heatExchangerDeficiency: improvement?.heatExchangerDeficiency ?? '',
    expansionTankDeficiency: improvement?.expansionTankDeficiency ?? '',
    pumpDeficiency: improvement?.pumpDeficiency ?? '',
    renewableEnergySystemDeficiency: improvement?.renewableEnergySystemDeficiency ?? '',
    packageAirConditionerDeficiency: improvement?.packageAirConditionerDeficiency ?? '',
    precisionAirConditionerDeficiency: improvement?.precisionAirConditionerDeficiency ?? '',
    airHandlingUnitDeficiency: improvement?.airHandlingUnitDeficiency ?? '',
    fanCoilUnitDeficiency: improvement?.fanCoilUnitDeficiency ?? '',
    ventilationSystemDeficiency: improvement?.ventilationSystemDeficiency ?? '',
    filterDeficiency: improvement?.filterDeficiency ?? '',
    sanitaryFacilityDeficiency: improvement?.sanitaryFacilityDeficiency ?? '',
    hotWaterSupplyDeficiency: improvement?.hotWaterSupplyDeficiency ?? '',
    waterTankDeficiency: improvement?.waterTankDeficiency ?? '',
    drainageDeficiency: improvement?.drainageDeficiency ?? '',
    sewageTreatmentDeficiency: improvement?.sewageTreatmentDeficiency ?? '',
    waterReuseDeficiency: improvement?.waterReuseDeficiency ?? '',
    pipeLineDeficiency: improvement?.pipeLineDeficiency ?? '',
    ductDeficiency: improvement?.ductDeficiency ?? '',
    insulationDeficiency: improvement?.insulationDeficiency ?? '',
    automaticControlDeficiency: improvement?.automaticControlDeficiency ?? '',
    noiseVibrationSeismicDeficiency: improvement?.noiseVibrationSeismicDeficiency ?? '',

    // Deficiency 및 Opinion 필드는 ''으로 초기화
    refrigeratorImprovement: improvement?.refrigeratorImprovement ?? '',
    coolingTowerImprovement: improvement?.coolingTowerImprovement ?? '',
    thermalStorageImprovement: improvement?.thermalStorageImprovement ?? '',
    boilerImprovement: improvement?.boilerImprovement ?? '',
    heatExchangerImprovement: improvement?.heatExchangerImprovement ?? '',
    expansionTankImprovement: improvement?.expansionTankImprovement ?? '',
    pumpImprovement: improvement?.pumpImprovement ?? '',
    renewableEnergySystemImprovement: improvement?.renewableEnergySystemImprovement ?? '',
    packageAirConditionerImprovement: improvement?.packageAirConditionerImprovement ?? '',
    precisionAirConditionerImprovement: improvement?.precisionAirConditionerImprovement ?? '',
    airHandlingUnitImprovement: improvement?.airHandlingUnitImprovement ?? '',
    fanCoilUnitImprovement: improvement?.fanCoilUnitImprovement ?? '',
    ventilationSystemImprovement: improvement?.ventilationSystemImprovement ?? '',
    filterImprovement: improvement?.filterImprovement ?? '',
    sanitaryFacilityImprovement: improvement?.sanitaryFacilityImprovement ?? '',
    hotWaterSupplyImprovement: improvement?.hotWaterSupplyImprovement ?? '',
    waterTankImprovement: improvement?.waterTankImprovement ?? '',
    drainageImprovement: improvement?.drainageImprovement ?? '',
    sewageTreatmentImprovement: improvement?.sewageTreatmentImprovement ?? '',
    waterReuseImprovement: improvement?.waterReuseImprovement ?? '',
    pipeLineImprovement: improvement?.pipeLineImprovement ?? '',
    ductImprovement: improvement?.ductImprovement ?? '',
    insulationImprovement: improvement?.insulationImprovement ?? '',
    automaticControlImprovement: improvement?.automaticControlImprovement ?? '',
    noiseVibrationSeismicImprovement: improvement?.noiseVibrationSeismicImprovement ?? '',

    note: improvement?.note ?? ''
  } as MachinePerformanceReviewImprovementResponseDtoType
}

export function makeYearlyPlanSeed(yearlyPlan?: MachinePerformanceReviewYearlyPlanResponseDtoType) {
  return {
    refrigeratorResult: yearlyPlan?.refrigeratorResult ?? 'NONE',
    coolingTowerResult: yearlyPlan?.coolingTowerResult ?? 'NONE',
    thermalStorageResult: yearlyPlan?.thermalStorageResult ?? 'NONE',
    boilerResult: yearlyPlan?.boilerResult ?? 'NONE',
    heatExchangerResult: yearlyPlan?.heatExchangerResult ?? 'NONE',
    expansionTankResult: yearlyPlan?.expansionTankResult ?? 'NONE',
    pumpResult: yearlyPlan?.pumpResult ?? 'NONE',
    renewableEnergySystemResult: yearlyPlan?.renewableEnergySystemResult ?? 'NONE',
    packageAirConditionerResult: yearlyPlan?.packageAirConditionerResult ?? 'NONE',
    precisionAirConditionerResult: yearlyPlan?.precisionAirConditionerResult ?? 'NONE',
    airHandlingUnitResult: yearlyPlan?.airHandlingUnitResult ?? 'NONE',
    fanCoilUnitResult: yearlyPlan?.fanCoilUnitResult ?? 'NONE',
    ventilationSystemResult: yearlyPlan?.ventilationSystemResult ?? 'NONE',
    filterResult: yearlyPlan?.filterResult ?? 'NONE',
    sanitaryFacilityResult: yearlyPlan?.sanitaryFacilityResult ?? 'NONE',
    hotWaterSupplyResult: yearlyPlan?.hotWaterSupplyResult ?? 'NONE',
    waterTankResult: yearlyPlan?.waterTankResult ?? 'NONE',
    drainageResult: yearlyPlan?.drainageResult ?? 'NONE',
    sewageTreatmentResult: yearlyPlan?.sewageTreatmentResult ?? 'NONE',
    waterReuseResult: yearlyPlan?.waterReuseResult ?? 'NONE',
    pipeLineResult: yearlyPlan?.pipeLineResult ?? 'NONE',
    ductResult: yearlyPlan?.ductResult ?? 'NONE',
    insulationResult: yearlyPlan?.insulationResult ?? 'NONE',
    automaticControlResult: yearlyPlan?.automaticControlResult ?? 'NONE',
    noiseVibrationSeismicResult: yearlyPlan?.noiseVibrationSeismicResult ?? 'NONE',

    // Deficiency 및 Opinion 필드는 ''으로 초기화
    refrigeratorDeficiency: yearlyPlan?.refrigeratorDeficiency ?? '',
    coolingTowerDeficiency: yearlyPlan?.coolingTowerDeficiency ?? '',
    thermalStorageDeficiency: yearlyPlan?.thermalStorageDeficiency ?? '',
    boilerDeficiency: yearlyPlan?.boilerDeficiency ?? '',
    heatExchangerDeficiency: yearlyPlan?.heatExchangerDeficiency ?? '',
    expansionTankDeficiency: yearlyPlan?.expansionTankDeficiency ?? '',
    pumpDeficiency: yearlyPlan?.pumpDeficiency ?? '',
    renewableEnergySystemDeficiency: yearlyPlan?.renewableEnergySystemDeficiency ?? '',
    packageAirConditionerDeficiency: yearlyPlan?.packageAirConditionerDeficiency ?? '',
    precisionAirConditionerDeficiency: yearlyPlan?.precisionAirConditionerDeficiency ?? '',
    airHandlingUnitDeficiency: yearlyPlan?.airHandlingUnitDeficiency ?? '',
    fanCoilUnitDeficiency: yearlyPlan?.fanCoilUnitDeficiency ?? '',
    ventilationSystemDeficiency: yearlyPlan?.ventilationSystemDeficiency ?? '',
    filterDeficiency: yearlyPlan?.filterDeficiency ?? '',
    sanitaryFacilityDeficiency: yearlyPlan?.sanitaryFacilityDeficiency ?? '',
    hotWaterSupplyDeficiency: yearlyPlan?.hotWaterSupplyDeficiency ?? '',
    waterTankDeficiency: yearlyPlan?.waterTankDeficiency ?? '',
    drainageDeficiency: yearlyPlan?.drainageDeficiency ?? '',
    sewageTreatmentDeficiency: yearlyPlan?.sewageTreatmentDeficiency ?? '',
    waterReuseDeficiency: yearlyPlan?.waterReuseDeficiency ?? '',
    pipeLineDeficiency: yearlyPlan?.pipeLineDeficiency ?? '',
    ductDeficiency: yearlyPlan?.ductDeficiency ?? '',
    insulationDeficiency: yearlyPlan?.insulationDeficiency ?? '',
    automaticControlDeficiency: yearlyPlan?.automaticControlDeficiency ?? '',
    noiseVibrationSeismicDeficiency: yearlyPlan?.noiseVibrationSeismicDeficiency ?? '',

    // PlanYear 필드 초기화 (모두 'NONE')
    refrigeratorPlanYear1: yearlyPlan?.refrigeratorPlanYear1 ?? 'NONE',
    refrigeratorPlanYear2: yearlyPlan?.refrigeratorPlanYear2 ?? 'NONE',
    refrigeratorPlanYear3: yearlyPlan?.refrigeratorPlanYear3 ?? 'NONE',
    refrigeratorPlanYear4: yearlyPlan?.refrigeratorPlanYear4 ?? 'NONE',
    refrigeratorPlanYear5: yearlyPlan?.refrigeratorPlanYear5 ?? 'NONE',

    coolingTowerPlanYear1: yearlyPlan?.coolingTowerPlanYear1 ?? 'NONE',
    coolingTowerPlanYear2: yearlyPlan?.coolingTowerPlanYear2 ?? 'NONE',
    coolingTowerPlanYear3: yearlyPlan?.coolingTowerPlanYear3 ?? 'NONE',
    coolingTowerPlanYear4: yearlyPlan?.coolingTowerPlanYear4 ?? 'NONE',
    coolingTowerPlanYear5: yearlyPlan?.coolingTowerPlanYear5 ?? 'NONE',

    thermalStoragePlanYear1: yearlyPlan?.thermalStoragePlanYear1 ?? 'NONE',
    thermalStoragePlanYear2: yearlyPlan?.thermalStoragePlanYear2 ?? 'NONE',
    thermalStoragePlanYear3: yearlyPlan?.thermalStoragePlanYear3 ?? 'NONE',
    thermalStoragePlanYear4: yearlyPlan?.thermalStoragePlanYear4 ?? 'NONE',
    thermalStoragePlanYear5: yearlyPlan?.thermalStoragePlanYear5 ?? 'NONE',

    boilerPlanYear1: yearlyPlan?.boilerPlanYear1 ?? 'NONE',
    boilerPlanYear2: yearlyPlan?.boilerPlanYear2 ?? 'NONE',
    boilerPlanYear3: yearlyPlan?.boilerPlanYear3 ?? 'NONE',
    boilerPlanYear4: yearlyPlan?.boilerPlanYear4 ?? 'NONE',
    boilerPlanYear5: yearlyPlan?.boilerPlanYear5 ?? 'NONE',

    heatExchangerPlanYear1: yearlyPlan?.heatExchangerPlanYear1 ?? 'NONE',
    heatExchangerPlanYear2: yearlyPlan?.heatExchangerPlanYear2 ?? 'NONE',
    heatExchangerPlanYear3: yearlyPlan?.heatExchangerPlanYear3 ?? 'NONE',
    heatExchangerPlanYear4: yearlyPlan?.heatExchangerPlanYear4 ?? 'NONE',
    heatExchangerPlanYear5: yearlyPlan?.heatExchangerPlanYear5 ?? 'NONE',

    expansionTankPlanYear1: yearlyPlan?.expansionTankPlanYear1 ?? 'NONE',
    expansionTankPlanYear2: yearlyPlan?.expansionTankPlanYear2 ?? 'NONE',
    expansionTankPlanYear3: yearlyPlan?.expansionTankPlanYear3 ?? 'NONE',
    expansionTankPlanYear4: yearlyPlan?.expansionTankPlanYear4 ?? 'NONE',
    expansionTankPlanYear5: yearlyPlan?.expansionTankPlanYear5 ?? 'NONE',

    pumpPlanYear1: yearlyPlan?.pumpPlanYear1 ?? 'NONE',
    pumpPlanYear2: yearlyPlan?.pumpPlanYear2 ?? 'NONE',
    pumpPlanYear3: yearlyPlan?.pumpPlanYear3 ?? 'NONE',
    pumpPlanYear4: yearlyPlan?.pumpPlanYear4 ?? 'NONE',
    pumpPlanYear5: yearlyPlan?.pumpPlanYear5 ?? 'NONE',

    renewableEnergySystemPlanYear1: yearlyPlan?.renewableEnergySystemPlanYear1 ?? 'NONE',
    renewableEnergySystemPlanYear2: yearlyPlan?.renewableEnergySystemPlanYear2 ?? 'NONE',
    renewableEnergySystemPlanYear3: yearlyPlan?.renewableEnergySystemPlanYear3 ?? 'NONE',
    renewableEnergySystemPlanYear4: yearlyPlan?.renewableEnergySystemPlanYear4 ?? 'NONE',
    renewableEnergySystemPlanYear5: yearlyPlan?.renewableEnergySystemPlanYear5 ?? 'NONE',

    packageAirConditionerPlanYear1: yearlyPlan?.packageAirConditionerPlanYear1 ?? 'NONE',
    packageAirConditionerPlanYear2: yearlyPlan?.packageAirConditionerPlanYear2 ?? 'NONE',
    packageAirConditionerPlanYear3: yearlyPlan?.packageAirConditionerPlanYear3 ?? 'NONE',
    packageAirConditionerPlanYear4: yearlyPlan?.packageAirConditionerPlanYear4 ?? 'NONE',
    packageAirConditionerPlanYear5: yearlyPlan?.packageAirConditionerPlanYear5 ?? 'NONE',

    precisionAirConditionerPlanYear1: yearlyPlan?.precisionAirConditionerPlanYear1 ?? 'NONE',
    precisionAirConditionerPlanYear2: yearlyPlan?.precisionAirConditionerPlanYear2 ?? 'NONE',
    precisionAirConditionerPlanYear3: yearlyPlan?.precisionAirConditionerPlanYear3 ?? 'NONE',
    precisionAirConditionerPlanYear4: yearlyPlan?.precisionAirConditionerPlanYear4 ?? 'NONE',
    precisionAirConditionerPlanYear5: yearlyPlan?.precisionAirConditionerPlanYear5 ?? 'NONE',

    airHandlingUnitPlanYear1: yearlyPlan?.airHandlingUnitPlanYear1 ?? 'NONE',
    airHandlingUnitPlanYear2: yearlyPlan?.airHandlingUnitPlanYear2 ?? 'NONE',
    airHandlingUnitPlanYear3: yearlyPlan?.airHandlingUnitPlanYear3 ?? 'NONE',
    airHandlingUnitPlanYear4: yearlyPlan?.airHandlingUnitPlanYear4 ?? 'NONE',
    airHandlingUnitPlanYear5: yearlyPlan?.airHandlingUnitPlanYear5 ?? 'NONE',

    fanCoilUnitPlanYear1: yearlyPlan?.fanCoilUnitPlanYear1 ?? 'NONE',
    fanCoilUnitPlanYear2: yearlyPlan?.fanCoilUnitPlanYear2 ?? 'NONE',
    fanCoilUnitPlanYear3: yearlyPlan?.fanCoilUnitPlanYear3 ?? 'NONE',
    fanCoilUnitPlanYear4: yearlyPlan?.fanCoilUnitPlanYear4 ?? 'NONE',
    fanCoilUnitPlanYear5: yearlyPlan?.fanCoilUnitPlanYear5 ?? 'NONE',

    ventilationSystemPlanYear1: yearlyPlan?.ventilationSystemPlanYear1 ?? 'NONE',
    ventilationSystemPlanYear2: yearlyPlan?.ventilationSystemPlanYear2 ?? 'NONE',
    ventilationSystemPlanYear3: yearlyPlan?.ventilationSystemPlanYear3 ?? 'NONE',
    ventilationSystemPlanYear4: yearlyPlan?.ventilationSystemPlanYear4 ?? 'NONE',
    ventilationSystemPlanYear5: yearlyPlan?.ventilationSystemPlanYear5 ?? 'NONE',

    filterPlanYear1: yearlyPlan?.filterPlanYear1 ?? 'NONE',
    filterPlanYear2: yearlyPlan?.filterPlanYear2 ?? 'NONE',
    filterPlanYear3: yearlyPlan?.filterPlanYear3 ?? 'NONE',
    filterPlanYear4: yearlyPlan?.filterPlanYear4 ?? 'NONE',
    filterPlanYear5: yearlyPlan?.filterPlanYear5 ?? 'NONE',

    sanitaryFacilityPlanYear1: yearlyPlan?.sanitaryFacilityPlanYear1 ?? 'NONE',
    sanitaryFacilityPlanYear2: yearlyPlan?.sanitaryFacilityPlanYear2 ?? 'NONE',
    sanitaryFacilityPlanYear3: yearlyPlan?.sanitaryFacilityPlanYear3 ?? 'NONE',
    sanitaryFacilityPlanYear4: yearlyPlan?.sanitaryFacilityPlanYear4 ?? 'NONE',
    sanitaryFacilityPlanYear5: yearlyPlan?.sanitaryFacilityPlanYear5 ?? 'NONE',

    hotWaterSupplyPlanYear1: yearlyPlan?.hotWaterSupplyPlanYear1 ?? 'NONE',
    hotWaterSupplyPlanYear2: yearlyPlan?.hotWaterSupplyPlanYear2 ?? 'NONE',
    hotWaterSupplyPlanYear3: yearlyPlan?.hotWaterSupplyPlanYear3 ?? 'NONE',
    hotWaterSupplyPlanYear4: yearlyPlan?.hotWaterSupplyPlanYear4 ?? 'NONE',
    hotWaterSupplyPlanYear5: yearlyPlan?.hotWaterSupplyPlanYear5 ?? 'NONE',

    waterTankPlanYear1: yearlyPlan?.waterTankPlanYear1 ?? 'NONE',
    waterTankPlanYear2: yearlyPlan?.waterTankPlanYear2 ?? 'NONE',
    waterTankPlanYear3: yearlyPlan?.waterTankPlanYear3 ?? 'NONE',
    waterTankPlanYear4: yearlyPlan?.waterTankPlanYear4 ?? 'NONE',
    waterTankPlanYear5: yearlyPlan?.waterTankPlanYear5 ?? 'NONE',

    drainagePlanYear1: yearlyPlan?.drainagePlanYear1 ?? 'NONE',
    drainagePlanYear2: yearlyPlan?.drainagePlanYear2 ?? 'NONE',
    drainagePlanYear3: yearlyPlan?.drainagePlanYear3 ?? 'NONE',
    drainagePlanYear4: yearlyPlan?.drainagePlanYear4 ?? 'NONE',
    drainagePlanYear5: yearlyPlan?.drainagePlanYear5 ?? 'NONE',

    sewageTreatmentPlanYear1: yearlyPlan?.sewageTreatmentPlanYear1 ?? 'NONE',
    sewageTreatmentPlanYear2: yearlyPlan?.sewageTreatmentPlanYear2 ?? 'NONE',
    sewageTreatmentPlanYear3: yearlyPlan?.sewageTreatmentPlanYear3 ?? 'NONE',
    sewageTreatmentPlanYear4: yearlyPlan?.sewageTreatmentPlanYear4 ?? 'NONE',
    sewageTreatmentPlanYear5: yearlyPlan?.sewageTreatmentPlanYear5 ?? 'NONE',

    waterReusePlanYear1: yearlyPlan?.waterReusePlanYear1 ?? 'NONE',
    waterReusePlanYear2: yearlyPlan?.waterReusePlanYear2 ?? 'NONE',
    waterReusePlanYear3: yearlyPlan?.waterReusePlanYear3 ?? 'NONE',
    waterReusePlanYear4: yearlyPlan?.waterReusePlanYear4 ?? 'NONE',
    waterReusePlanYear5: yearlyPlan?.waterReusePlanYear5 ?? 'NONE',

    pipeLinePlanYear1: yearlyPlan?.pipeLinePlanYear1 ?? 'NONE',
    pipeLinePlanYear2: yearlyPlan?.pipeLinePlanYear2 ?? 'NONE',
    pipeLinePlanYear3: yearlyPlan?.pipeLinePlanYear3 ?? 'NONE',
    pipeLinePlanYear4: yearlyPlan?.pipeLinePlanYear4 ?? 'NONE',
    pipeLinePlanYear5: yearlyPlan?.pipeLinePlanYear5 ?? 'NONE',

    ductPlanYear1: yearlyPlan?.ductPlanYear1 ?? 'NONE',
    ductPlanYear2: yearlyPlan?.ductPlanYear2 ?? 'NONE',
    ductPlanYear3: yearlyPlan?.ductPlanYear3 ?? 'NONE',
    ductPlanYear4: yearlyPlan?.ductPlanYear4 ?? 'NONE',
    ductPlanYear5: yearlyPlan?.ductPlanYear5 ?? 'NONE',

    insulationPlanYear1: yearlyPlan?.insulationPlanYear1 ?? 'NONE',
    insulationPlanYear2: yearlyPlan?.insulationPlanYear2 ?? 'NONE',
    insulationPlanYear3: yearlyPlan?.insulationPlanYear3 ?? 'NONE',
    insulationPlanYear4: yearlyPlan?.insulationPlanYear4 ?? 'NONE',
    insulationPlanYear5: yearlyPlan?.insulationPlanYear5 ?? 'NONE',

    automaticControlPlanYear1: yearlyPlan?.automaticControlPlanYear1 ?? 'NONE',
    automaticControlPlanYear2: yearlyPlan?.automaticControlPlanYear2 ?? 'NONE',
    automaticControlPlanYear3: yearlyPlan?.automaticControlPlanYear3 ?? 'NONE',
    automaticControlPlanYear4: yearlyPlan?.automaticControlPlanYear4 ?? 'NONE',
    automaticControlPlanYear5: yearlyPlan?.automaticControlPlanYear5 ?? 'NONE',

    noiseVibrationSeismicPlanYear1: yearlyPlan?.noiseVibrationSeismicPlanYear1 ?? 'NONE',
    noiseVibrationSeismicPlanYear2: yearlyPlan?.noiseVibrationSeismicPlanYear2 ?? 'NONE',
    noiseVibrationSeismicPlanYear3: yearlyPlan?.noiseVibrationSeismicPlanYear3 ?? 'NONE',
    noiseVibrationSeismicPlanYear4: yearlyPlan?.noiseVibrationSeismicPlanYear4 ?? 'NONE',
    noiseVibrationSeismicPlanYear5: yearlyPlan?.noiseVibrationSeismicPlanYear5 ?? 'NONE',

    note: yearlyPlan?.note ?? ''
  } as MachinePerformanceReviewYearlyPlanResponseDtoType
}
